apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: odhservicemonitor
  labels:
    team: opendatahub
  namespace: opendatahub
spec:
  selector: {}
  endpoints:
    - port: web # odh-operator, Argo
    - bearerTokenSecret:
        key: PROMETHEUS_API_TOKEN
        name: jupyterhub
      port: 8080-tcp # Jupyterhub
      path: "/metrics"
  selector:
    matchLabels:
      opendatahub.io/component: "true"
