managers:
  - name: version
    configuration:
      maintainers:
        - crobby
        - vpavlin
        - lavlas
        - nakfour
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
