apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub-ldap-jupyterhub
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      overlays:
      - rolebased
      parameters:
        - name: s3_endpoint_url
          value: s3-us-west-2.amazonaws
        - name: jupyterhub_groups_config
          value: jhubgroups
        - name: role_mount_configmap
          value: ldap-role-mount
      repoRef:
        name: manifests
        path: jupyterhub/jupyterhub
    name: jupyterhub
  - kustomizeConfig:
      overlays:
      - additional
      repoRef:
        name: manifests
        path: jupyterhub/notebook-images
    name: notebook-images
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-dashboard
    name: odh-dashboard
  repos:
  - name: kf-manifests
    uri: https://github.com/opendatahub-io/manifests/tarball/v1.0-branch-openshift
  - name: manifests
    uri: https://github.com/chirag1603/odh-manifests/tarball/patch-1
  version: patch-1
