---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ceph-nano-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ceph-nano-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-nano-secrets
subjects:
  - kind: ServiceAccount
    name: ceph-nano
