apiVersion: batch/v1
kind: Job
metadata:
  name: superset-db-init
  namespace: opendatahub
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: superset-db-init
    spec:
      containers:
        - name: superset-init
          envFrom:
            - configMapRef:
                name: superset
            - secretRef:
                name: superset-secret
          image: quay.io/aiops/superset:v0.30
          imagePullPolicy: Always
          command:
            - /bin/sh
            - /usr/local/bin/superset-init
            - --username $(SUPERSET_ADMIN_USER) --firstname $(SUPERSET_ADMIN_FNAME) --lastname $(SUPERSET_ADMIN_LNAME) --email $(SUPERSET_ADMIN_EMAIL) --password $(SUPERSET_ADMIN_PASSWORD)
          volumeMounts:
            - mountPath: /var/lib/superset
              name: superset-data
            - mountPath: /etc/superset
              name: superset-config
      volumes:
        - name: superset-data
          persistentVolumeClaim:
            claimName: superset-data
        - configMap:
            defaultMode: 420
            items:
              - key: superset_config.py
                path: superset_config.py
            name: superset
          name: superset-config
      restartPolicy: OnFailure
